/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package examen2dotrimestrejoaquinlopez;

import javax.swing.JOptionPane;

/**
 *
 * @author USUARIO
 */
public class CrearXml extends javax.swing.JFrame {

    //variables globales para gestionar las peliculas por generos
    int contadorAventura = 0;
    int contadorMisterio = 0;
    int contadorComedia = 0;

    /**
     * Creates new form CrearXml
     */
    public CrearXml() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        tfTitulo = new javax.swing.JTextField();
        tfDuracion = new javax.swing.JTextField();
        tfTrailer = new javax.swing.JTextField();
        cbGeneros = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        taListado = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Noto Serif", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CREAR XML");

        jLabel2.setFont(new java.awt.Font("Noto Serif", 0, 10)); // NOI18N
        jLabel2.setText("GENERO");

        jLabel3.setFont(new java.awt.Font("Noto Serif", 0, 10)); // NOI18N
        jLabel3.setText("TITULO");

        jLabel4.setFont(new java.awt.Font("Noto Serif", 0, 10)); // NOI18N
        jLabel4.setText("DURACION");

        jLabel5.setFont(new java.awt.Font("Noto Serif", 0, 10)); // NOI18N
        jLabel5.setText("TRAILER");

        jButton1.setFont(new java.awt.Font("Noto Serif", 0, 10)); // NOI18N
        jButton1.setText("AGREGAR PELICULA");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tfTitulo.setFont(new java.awt.Font("Noto Serif", 0, 10)); // NOI18N
        tfTitulo.setForeground(new java.awt.Color(0, 0, 0));

        tfDuracion.setFont(new java.awt.Font("Noto Serif", 0, 10)); // NOI18N
        tfDuracion.setForeground(new java.awt.Color(0, 0, 0));

        tfTrailer.setFont(new java.awt.Font("Noto Serif", 0, 10)); // NOI18N
        tfTrailer.setForeground(new java.awt.Color(0, 0, 0));

        cbGeneros.setFont(new java.awt.Font("Noto Serif", 0, 10)); // NOI18N
        cbGeneros.setForeground(new java.awt.Color(0, 0, 0));
        cbGeneros.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MISTERIO", "AVENTURA", "COMEDIA" }));

        taListado.setColumns(20);
        taListado.setRows(5);
        jScrollPane1.setViewportView(taListado);

        jButton2.setFont(new java.awt.Font("Noto Serif", 0, 10)); // NOI18N
        jButton2.setText("GENERAR XML");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfDuracion)
                            .addComponent(tfTrailer)
                            .addComponent(tfTitulo)
                            .addComponent(cbGeneros, 0, 274, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(130, 130, 130)
                                .addComponent(jButton1))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jButton2)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 380, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 8, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbGeneros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfTrailer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        //contadores para cada genero de la lista

        //verificaciones de campos antes de agregar una pelicula a la lista.
        String titulo = tfTitulo.getText().toString();
        String duracion = tfDuracion.getText().toString();
        String genero = cbGeneros.getSelectedItem().toString();
        String linkPelicula = tfTrailer.getText().toString();

        if (titulo.isEmpty()) {
            //error si el campo titulo esta vacio
            JOptionPane.showMessageDialog(this, "Titulo Vacio");
            tfTitulo.requestFocus();
        } else if (!duracion.matches("\\d+") && !duracion.isEmpty()) { // \\d+ es igual a [0-9]+
            // Error: duración no es entero positivo o vacio
            JOptionPane.showMessageDialog(this, "El numero ingresadod debe ser un entero y el campo no debe estar vacio");
        } else if (!(linkPelicula.startsWith("http://") || linkPelicula.startsWith("https://")) && !linkPelicula.isEmpty()) {
            // Error: URL mal formada
            JOptionPane.showMessageDialog(this, "Link incorrecto, debe comenzar por 'http://' o 'https://' y el campo debe estar con informacion");
        } // 2. Validaciones de límite por género (Punto 4)
        else if (genero.equals("AVENTURA") && contadorAventura >= 3) {
            JOptionPane.showMessageDialog(this, "Límite alcanzado: Ya hay 3 películas de Aventura.");
        } else if (genero.equals("COMEDIA") && contadorComedia >= 3) {
            JOptionPane.showMessageDialog(this, "Límite alcanzado: Ya hay 3 películas de Comedia.");
        } else if (genero.equals("MISTERIO") && contadorMisterio >= 3) {
            JOptionPane.showMessageDialog(this, "Límite alcanzado: Ya hay 3 películas de Misterio.");
        } // una vez confirmado que todos lo campos cumplen con las condiciones aumentamos el contador y agregamos al textArea
        else {
            // Incrementar contador según el género seleccionado
            if (genero.equals("Aventura")) {
                contadorAventura++;
            } else if (genero.equals("Comedia")) {
                contadorComedia++;
            } else if (genero.equals("Misterio")) {
                contadorMisterio++;
            }

            // Mostrar en el listado
            taListado.append("Título: " + titulo + " | Género: " + genero + " | Duración: " + duracion + " min.\n");
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearXml.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearXml.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearXml.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearXml.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearXml().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbGeneros;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea taListado;
    private javax.swing.JTextField tfDuracion;
    private javax.swing.JTextField tfTitulo;
    private javax.swing.JTextField tfTrailer;
    // End of variables declaration//GEN-END:variables
}
