/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package examen2dotrimestrejoaquinlopez;

import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author USUARIO
 */
public class CrearXml extends javax.swing.JFrame {

    // Variables globales para llevar la cuenta de cuántas películas hay de cada género
    int contadorAventura = 0;
    int contadorMisterio = 0;
    int contadorComedia = 0;

    // Lista dinámica (ArrayList) que guardará objetos de tipo 'Pelicula' en la memoria RAM
    ArrayList<Pelicula> listaPeliculas = new ArrayList<>();

    /**
     * Constructor de la ventana
     */
    public CrearXml() {
        initComponents(); // Inicializa los componentes visuales generados por el diseño

        // Configura que al cerrar esta ventana solo se cierre ella y no todo el programa
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);

        // Centra la ventana en la pantalla del usuario
        this.setLocationRelativeTo(null);

        // Define el tamaño inicial de la ventana
        setSize(800, 500);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        tfTitulo = new javax.swing.JTextField();
        tfDuracion = new javax.swing.JTextField();
        tfTrailer = new javax.swing.JTextField();
        cbGeneros = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        taListado = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Noto Serif", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CREAR XML");

        jLabel2.setFont(new java.awt.Font("Noto Serif", 0, 10)); // NOI18N
        jLabel2.setText("GENERO");

        jLabel3.setFont(new java.awt.Font("Noto Serif", 0, 10)); // NOI18N
        jLabel3.setText("TITULO");

        jLabel4.setFont(new java.awt.Font("Noto Serif", 0, 10)); // NOI18N
        jLabel4.setText("DURACION");

        jLabel5.setFont(new java.awt.Font("Noto Serif", 0, 10)); // NOI18N
        jLabel5.setText("TRAILER");

        jButton1.setFont(new java.awt.Font("Noto Serif", 0, 10)); // NOI18N
        jButton1.setText("AGREGAR PELICULA");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        tfTitulo.setFont(new java.awt.Font("Noto Serif", 0, 10)); // NOI18N
        tfTitulo.setForeground(new java.awt.Color(0, 0, 0));

        tfDuracion.setFont(new java.awt.Font("Noto Serif", 0, 10)); // NOI18N
        tfDuracion.setForeground(new java.awt.Color(0, 0, 0));

        tfTrailer.setFont(new java.awt.Font("Noto Serif", 0, 10)); // NOI18N
        tfTrailer.setForeground(new java.awt.Color(0, 0, 0));

        cbGeneros.setFont(new java.awt.Font("Noto Serif", 0, 10)); // NOI18N
        cbGeneros.setForeground(new java.awt.Color(0, 0, 0));
        cbGeneros.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MISTERIO", "AVENTURA", "COMEDIA" }));

        taListado.setColumns(20);
        taListado.setRows(5);
        jScrollPane1.setViewportView(taListado);

        jButton2.setFont(new java.awt.Font("Noto Serif", 0, 10)); // NOI18N
        jButton2.setText("GENERAR XML");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jButton2))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 79, Short.MAX_VALUE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfTrailer, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tfDuracion, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(tfTitulo)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(cbGeneros, javax.swing.GroupLayout.PREFERRED_SIZE, 680, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addGap(20, 20, 20))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(327, 327, 327)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(cbGeneros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfDuracion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfTrailer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Acción del botón "AGREGAR PELICULA"
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Captura los datos escritos por el usuario en los campos de texto
        String titulo = tfTitulo.getText().toString();
        String duracion = tfDuracion.getText().toString();
        String genero = cbGeneros.getSelectedItem().toString(); // Obtiene el género del ComboBox
        String linkPelicula = tfTrailer.getText().toString().toLowerCase(); // Convierte el link a minúsculas

        // --- VALIDACIONES DE CAMPOS VACÍOS O INCORRECTOS ---
        if (titulo.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Titulo Vacio");
            tfTitulo.requestFocus(); // Devuelve el foco al campo del título
        } // Valida que la duración sean números (\\d+) y no esté vacío
        else if (!duracion.matches("\\d+") && !duracion.isEmpty()) {
            JOptionPane.showMessageDialog(this, "El numero ingresadod debe ser un entero y el campo no debe estar vacio");
            tfDuracion.requestFocus();
        } // Valida que el link empiece con el protocolo correcto
        else if (!(linkPelicula.startsWith("http://") || linkPelicula.startsWith("https://")) && !linkPelicula.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Link incorrecto, debe comenzar por 'http://' o 'https://'");
            tfTrailer.requestFocus();
        } // --- VALIDACIÓN DE LÍMITES (MÁXIMO 3 POR GÉNERO) ---
        else if (genero.equals("AVENTURA") && contadorAventura >= 3) {
            JOptionPane.showMessageDialog(this, "Límite alcanzado: Ya hay 3 películas de Aventura.");
        } else if (genero.equals("COMEDIA") && contadorComedia >= 3) {
            JOptionPane.showMessageDialog(this, "Límite alcanzado: Ya hay 3 películas de Comedia.");
        } else if (genero.equals("MISTERIO") && contadorMisterio >= 3) {
            JOptionPane.showMessageDialog(this, "Límite alcanzado: Ya hay 3 películas de Misterio.");
        } // --- PROCESO DE AGREGAR SI TODO ESTÁ BIEN ---
        else {
            // Incrementa el contador específico según el género seleccionado
            if (genero.equals("AVENTURA")) {
                contadorAventura++;
            } else if (genero.equals("COMEDIA")) {
                contadorComedia++;
            } else if (genero.equals("MISTERIO")) {
                contadorMisterio++;
            }

            // Crea un nuevo objeto Pelicula y lo guarda en nuestro ArrayList global
            listaPeliculas.add(new Pelicula(titulo, duracion, genero, linkPelicula));

            // Agrega una línea de texto informativa al JTextArea (el listado visual)
            taListado.append("Título: " + titulo + " | Género: " + genero + " | Duración: " + duracion + " min." + " | Trailer: " + linkPelicula + "\n");

            // Borra el contenido de los campos para dejar espacio a la siguiente película
            tfDuracion.setText("");
            tfTitulo.setText("");
            tfTrailer.setText("");
        }


    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * Acción del botón "GENERAR XML"
     */
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:

        //Generacion de documentoXML
        if (contadorAventura != 3 || contadorComedia != 3 || contadorMisterio != 3) {
            JOptionPane.showMessageDialog(this, "Aún no puedes generar el XML. Faltan películas por agregar.");
        } else {
            try {
                // --- 1. PREPARACIÓN DEL DOCUMENTO ---

                // Crea la fábrica para poder construir el analizador de documentos XML
                javax.xml.parsers.DocumentBuilderFactory factory = javax.xml.parsers.DocumentBuilderFactory.newInstance();

                // Crea el constructor (builder) que nos permite generar un documento vacío en memoria
                javax.xml.parsers.DocumentBuilder builder = factory.newDocumentBuilder();

                // Crea el objeto 'doc', que es el lienzo en blanco donde dibujaremos nuestro árbol XML
                org.w3c.dom.Document doc = builder.newDocument();

                // --- 2. CREACIÓN DE LA ESTRUCTURA PRINCIPAL ---
                // Crea la etiqueta principal <peliculas> (el nodo raíz)
                org.w3c.dom.Element raiz = doc.createElement("peliculas");
                // Agrega la raíz al documento para que sea el punto de partida
                doc.appendChild(raiz);

                // Crea los tres nodos de categoría que agruparán a las películas
                org.w3c.dom.Element nodoMisterio = doc.createElement("misterio");
                org.w3c.dom.Element nodoAventura = doc.createElement("aventura");
                org.w3c.dom.Element nodoComedia = doc.createElement("comedia");

                // Engancha cada categoría debajo de la raíz <peliculas>
                raiz.appendChild(nodoMisterio);
                raiz.appendChild(nodoAventura);
                raiz.appendChild(nodoComedia);

                // --- 3. LLENADO DE DATOS (RECORRIENDO LA LISTA) ---
                // Empezamos a recorrer la lista de objetos 'Pelicula' que fuiste guardando al dar clic en "Agregar"
                for (Pelicula p : listaPeliculas) {

                    // Para cada objeto, creamos una etiqueta contenedora llamada <pelicula>
                    org.w3c.dom.Element nodoPeli = doc.createElement("pelicula");

                    // Crea el elemento <titulo>, le mete el texto del objeto y lo pega dentro de <pelicula>
                    org.w3c.dom.Element eTitulo = doc.createElement("titulo");
                    eTitulo.setTextContent(p.titulo);
                    nodoPeli.appendChild(eTitulo);

                    // Crea el elemento <duracion>, le mete el texto y lo pega dentro de <pelicula>
                    org.w3c.dom.Element eDuracion = doc.createElement("duracion");
                    eDuracion.setTextContent(p.duracion);
                    nodoPeli.appendChild(eDuracion);

                    // Crea el elemento <trailer>, le mete el texto de la URL y lo pega dentro de <pelicula>
                    org.w3c.dom.Element eTrailer = doc.createElement("trailer");
                    eTrailer.setTextContent(p.trailer);
                    nodoPeli.appendChild(eTrailer);

                    // --- 4. CLASIFICACIÓN POR GÉNERO ---
                    // Según el género que guardamos en el objeto, decidimos en qué categoría colgar la película
                    if (p.genero.equals("MISTERIO")) {
                        nodoMisterio.appendChild(nodoPeli); // Se va para <misterio>
                    } else if (p.genero.equals("AVENTURA")) {
                        nodoAventura.appendChild(nodoPeli); // Se va para <aventura>
                    } else if (p.genero.equals("COMEDIA")) {
                        nodoComedia.appendChild(nodoPeli);  // Se va para <comedia>
                    }
                }

                // --- 5. TRANSFORMACIÓN DE MEMORIA A ARCHIVO FÍSICO ---
                // Creamos la fábrica para transformar el árbol que está en RAM a un archivo de texto
                javax.xml.transform.TransformerFactory tf = javax.xml.transform.TransformerFactory.newInstance();
                javax.xml.transform.Transformer transformer = tf.newTransformer();

                // Configura el XML para que tenga sangrías (espacios) y no salga todo en una sola línea
                transformer.setOutputProperty(javax.xml.transform.OutputKeys.INDENT, "yes");
                // Define que la sangría sea de 4 espacios (esto lo hace legible como en tu imagen)
                transformer.setOutputProperty("{http://xml.apache.org/xslt}indent-amount", "4");

                // Define la fuente de los datos (nuestro documento 'doc')
                javax.xml.transform.dom.DOMSource origen = new javax.xml.transform.dom.DOMSource(doc);

                // Define el destino (un archivo llamado "peliculas.xml" en la carpeta del proyecto)
                java.io.File archivo = new java.io.File("peliculas.xml");
                javax.xml.transform.stream.StreamResult destino = new javax.xml.transform.stream.StreamResult(archivo);

                // Ejecuta la transformación real: escribe el archivo en el disco duro
                transformer.transform(origen, destino);

                // Avisa al usuario que todo salió bien
                javax.swing.JOptionPane.showMessageDialog(this, "Archivo peliculas.xml generado correctamente.");

            } catch (Exception ex) {
                // Si algo falla (permisos de archivo, errores de memoria), imprime el error y avisa
                ex.printStackTrace();
                javax.swing.JOptionPane.showMessageDialog(this, "Error al generar el XML.");
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearXml.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearXml.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearXml.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearXml.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearXml().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cbGeneros;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea taListado;
    private javax.swing.JTextField tfDuracion;
    private javax.swing.JTextField tfTitulo;
    private javax.swing.JTextField tfTrailer;
    // End of variables declaration//GEN-END:variables
}
