/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package examen2dotrimestrejoaquinlopez;

import javax.swing.JOptionPane;

/**
 *
 * @author USUARIO
 */
public class LeerXML extends javax.swing.JFrame {

    /**
     * Creates new form LeerXML
     */
    public LeerXML() {
        initComponents();
        //centramos el jframe
        this.setLocationRelativeTo(null);
        //set que al cerrar la ventana solo se cierre esta ventana y no el programa entero
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
        setSize(1200, 600);
        cargarDatos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPeliculas = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Noto Sans", 0, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel1.setText("LECTURA DE XML");

        tablaPeliculas.setBackground(new java.awt.Color(0, 102, 102));
        tablaPeliculas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "GENERO", "TITULO", "DURACION", "TRAILER"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaPeliculas.getTableHeader().setResizingAllowed(false);
        tablaPeliculas.getTableHeader().setReorderingAllowed(false);
        tablaPeliculas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaPeliculasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaPeliculas);

        jLabel2.setText("HACER CLICK EN LA FILA PARA MOSTRAR EL TRAILER DE LA PELICULA SELECCIONADA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 804, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addContainerGap(176, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tablaPeliculasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaPeliculasMouseClicked
        // TODO add your handling code here:
        int filaSeleccionada = tablaPeliculas.getSelectedRow();//
        String titulo = tablaPeliculas.getValueAt(filaSeleccionada, 1).toString();
        String url = tablaPeliculas.getValueAt(filaSeleccionada, 3).toString();

        int confirmacion = javax.swing.JOptionPane.showConfirmDialog(
                this,
                "¿Deseas abrir en tu navegador el tráiler de: " + titulo + "?",
                "Ver Tráiler", // Título de la ventana emergente
                javax.swing.JOptionPane.YES_NO_OPTION,
                javax.swing.JOptionPane.QUESTION_MESSAGE // Icono de pregunta
        );

        // 2. Evaluar la respuesta
        if (confirmacion == javax.swing.JOptionPane.YES_OPTION) {
            try {
                // Verificar si el sistema soporta abrir el navegador
                if (java.awt.Desktop.isDesktopSupported()) {
                    java.awt.Desktop desktop = java.awt.Desktop.getDesktop();
                    if (desktop.isSupported(java.awt.Desktop.Action.BROWSE)) {
                        // Aquí usamos la variable 'linkPelicula' o la que sacaste de la tabla
                        desktop.browse(new java.net.URI(url));
                    }
                }
            } catch (Exception e) {
                javax.swing.JOptionPane.showMessageDialog(this, "Error al intentar abrir el link: " + e.getMessage());
            }
        }
    }//GEN-LAST:event_tablaPeliculasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LeerXML.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LeerXML.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LeerXML.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LeerXML.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LeerXML().setVisible(true);
            }
        });
    }

    public void cargarDatos() {
        // 2. Preparar el parser XML
        try {
            javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tablaPeliculas.getModel();
            java.io.File archivo = new java.io.File("peliculas.xml");
            javax.xml.parsers.DocumentBuilderFactory dbFactory = javax.xml.parsers.DocumentBuilderFactory.newInstance();
            javax.xml.parsers.DocumentBuilder dBuilder = dbFactory.newDocumentBuilder();
            org.w3c.dom.Document doc = dBuilder.parse(archivo);
            doc.getDocumentElement().normalize();

            // 3. Obtener los nodos de los géneros (hijos de <peliculas>)
            org.w3c.dom.NodeList listaGeneros = doc.getDocumentElement().getChildNodes();

            // Recorrer los géneros (Misterio, Aventura, Comedia)
            for (int i = 0; i < listaGeneros.getLength(); i++) {
                org.w3c.dom.Node nodoGenero = listaGeneros.item(i);

                if (nodoGenero.getNodeType() == org.w3c.dom.Node.ELEMENT_NODE) {
                    String nombreGenero = nodoGenero.getNodeName().toUpperCase();

                    // Recorrer las películas dentro de este género
                    org.w3c.dom.NodeList listaPelis = nodoGenero.getChildNodes();
                    for (int j = 0; j < listaPelis.getLength(); j++) {
                        org.w3c.dom.Node nodoPeli = listaPelis.item(j);

                        if (nodoPeli.getNodeType() == org.w3c.dom.Node.ELEMENT_NODE) {
                            org.w3c.dom.Element e = (org.w3c.dom.Element) nodoPeli;

                            // Extraer datos
                            String titulo = e.getElementsByTagName("titulo").item(0).getTextContent();
                            String duracion = e.getElementsByTagName("duracion").item(0).getTextContent();
                            String url = e.getElementsByTagName("trailer").item(0).getTextContent();

                            // 4. AGREGAR FILA A LA TABLA
                            modelo.addRow(new Object[]{nombreGenero, titulo, duracion, url});
                        }
                    }
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
            javax.swing.JOptionPane.showMessageDialog(this, "Error al leer XML: " + e.getMessage());
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaPeliculas;
    // End of variables declaration//GEN-END:variables
}
