/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package examen2dotrimestrejoaquinlopez;

import java.awt.ComponentOrientation;
import javax.swing.JOptionPane;

/**
 *
 * @author USUARIO
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {

        initComponents();
        this.setSize(400, 400);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu = new javax.swing.JMenu();
        miCrearXML = new javax.swing.JMenuItem();
        miLeerXML = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jMenu.setText("Menu");

        miCrearXML.setText("CrearXML");
        miCrearXML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miCrearXMLActionPerformed(evt);
            }
        });
        jMenu.add(miCrearXML);

        miLeerXML.setText("LeerXML");
        miLeerXML.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miLeerXMLActionPerformed(evt);
            }
        });
        jMenu.add(miLeerXML);

        jMenuBar1.add(jMenu);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void miCrearXMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miCrearXMLActionPerformed
        // TODO add your handling code here:

        //metodo para mostrar la vista "Crear XML"
        //creamo una nueva vista
        CrearXml vistaCrear = new CrearXml();
        //hacemos la vista visible
        vistaCrear.setVisible(true);
    }//GEN-LAST:event_miCrearXMLActionPerformed

    private void miLeerXMLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miLeerXMLActionPerformed
        // TODO add your handling code here:

        //VERIFICAMOS SI EL ARCHIVO PELICULAS.XML EXISTE
        java.io.File archivo = new java.io.File("peliculas.xml");
        if (!archivo.exists()) {
            JOptionPane.showMessageDialog(this, "No se encuentra el archivo peliculas.xml\ndebes crear el documentoXML primero");
            return;
        } else {
            //metodo para mostrar vista LeerXml

            //creacion del modelo vista "LeerXml"
            LeerXML vistaLeerXml = new LeerXML();

            vistaLeerXml.setVisible(true);
        }

    }//GEN-LAST:event_miLeerXMLActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem miCrearXML;
    private javax.swing.JMenuItem miLeerXML;
    // End of variables declaration//GEN-END:variables
}
